---
  name: ci

  on:
    pull_request:
    push:
      # branches:
      #   - master

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@master
        - name: Install Chef
          uses: actionshub/chef-install@master
        - name: Cookstyle Sweep
          run: cookstyle .
        - name: Install Kitchen Docker
          run: chef exec gem install kitchen-docker
          env:
            CHEF_LICENSE: accept-no-persist
        - name: Kitchen Test
          run: kitchen test --color
          env:
            CHEF_LICENSE: accept-no-persist
